var tree = [["AuthBucket",,"",
                [["Bundle",,"",
                [["OAuth2Bundle","AuthBucket\/Bundle\/OAuth2Bundle.html","",
                [["Controller","AuthBucket\/Bundle\/OAuth2Bundle\/Controller.html","",
                [["AuthorizeController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/AuthorizeController.html"," < Controller",
                [        ]],["DebugController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/DebugController.html"," < Controller",
                [        ]],["TokenController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/TokenController.html"," < Controller",
                [        ]]        ]],["DependencyInjection","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection.html","",
                [["Security",,"",
                [["Factory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory.html","",
                [["ResourceFactory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/ResourceFactory.html","",
                [        ]],["TokenFactory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/TokenFactory.html","",
                [        ]]        ]]        ]],["AuthBucketOAuth2Extension","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/AuthBucketOAuth2Extension.html"," < Extension",
                [        ]],["Configuration","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Configuration.html","",
                [        ]]        ]],["Entity","AuthBucket\/Bundle\/OAuth2Bundle\/Entity.html","",
                [["AccessToken","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AccessToken.html","",
                [        ]],["AccessTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AccessTokenRepository.html"," < EntityRepository",
                [        ]],["Authorize","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Authorize.html","",
                [        ]],["AuthorizeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AuthorizeRepository.html"," < EntityRepository",
                [        ]],["Client","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Client.html","",
                [        ]],["ClientRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ClientRepository.html"," < EntityRepository",
                [        ]],["Code","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Code.html","",
                [        ]],["CodeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/CodeRepository.html"," < EntityRepository",
                [        ]],["ModelManagerFactory","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ModelManagerFactory.html","",
                [        ]],["RefreshToken","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/RefreshToken.html","",
                [        ]],["RefreshTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/RefreshTokenRepository.html"," < EntityRepository",
                [        ]],["Scope","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Scope.html","",
                [        ]],["ScopeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ScopeRepository.html"," < EntityRepository",
                [        ]]        ]],["AuthBucketOAuth2Bundle","AuthBucket\/Bundle\/OAuth2Bundle\/AuthBucketOAuth2Bundle.html"," < Bundle",
                [        ]]        ]]        ]]        ]]        ]

