<?php

/**
 * This file is part of the authbucket/oauth2-symfony-bundle package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AuthBucket\Bundle\OAuth2Bundle\Entity;

use AuthBucket\OAuth2\Model\ModelInterface;
use AuthBucket\OAuth2\Model\ModelManagerInterface;
use Doctrine\ORM\EntityRepository;

/**
 * AbstractEntityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
trait ModelManagerEntityRepository
{
    public function createModel(ModelInterface $model)
    {
        $this->getEntityManager()->persist($model);
        $this->getEntityManager()->flush();

        return $model;
    }

    public function readModelAll()
    {
        return $this->findAll();
    }

    public function readModelBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }

    public function readModelOneBy(array $criteria, array $orderBy = null)
    {
        return $this->findOneBy($criteria, $orderBy);
    }

    public function updateModel(ModelInterface $model)
    {
        $this->getEntityManager()->flush();

        return $model;
    }

    public function deleteModel(ModelInterface $model)
    {
        $this->getEntityManager()->remove($model);
        $this->getEntityManager()->flush();

        return $model;
    }
}
