var tree = [["Pantarei",,"",
                [["Bundle",,"",
                [["Oauth2Bundle","Pantarei\/Bundle\/Oauth2Bundle.html","",
                [["Controller","Pantarei\/Bundle\/Oauth2Bundle\/Controller.html","",
                [["AuthorizeController","Pantarei\/Bundle\/Oauth2Bundle\/Controller\/AuthorizeController.html"," < Controller",
                [        ]],["ResourceController","Pantarei\/Bundle\/Oauth2Bundle\/Controller\/ResourceController.html"," < Controller",
                [        ]],["TokenController","Pantarei\/Bundle\/Oauth2Bundle\/Controller\/TokenController.html"," < Controller",
                [        ]]        ]],["DependencyInjection","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection.html","",
                [["Security",,"",
                [["Factory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory.html","",
                [["ResourceFactory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory\/ResourceFactory.html","",
                [        ]],["TokenFactory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory\/TokenFactory.html","",
                [        ]]        ]]        ]],["Configuration","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Configuration.html","",
                [        ]],["Oauth2Extension","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Oauth2Extension.html"," < Extension",
                [        ]]        ]],["Entity","Pantarei\/Bundle\/Oauth2Bundle\/Entity.html","",
                [["AccessToken","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/AccessToken.html","",
                [        ]],["AccessTokenManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/AccessTokenManager.html"," < EntityRepository",
                [        ]],["Authorize","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/Authorize.html","",
                [        ]],["AuthorizeManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/AuthorizeManager.html"," < EntityRepository",
                [        ]],["Client","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/Client.html","",
                [        ]],["ClientManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/ClientManager.html"," < EntityRepository",
                [        ]],["Code","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/Code.html","",
                [        ]],["CodeManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/CodeManager.html"," < EntityRepository",
                [        ]],["ModelManagerFactory","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/ModelManagerFactory.html","",
                [        ]],["RefreshToken","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/RefreshToken.html","",
                [        ]],["RefreshTokenManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/RefreshTokenManager.html"," < EntityRepository",
                [        ]],["Scope","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/Scope.html","",
                [        ]],["ScopeManager","Pantarei\/Bundle\/Oauth2Bundle\/Entity\/ScopeManager.html"," < EntityRepository",
                [        ]]        ]],["Oauth2Bundle","Pantarei\/Bundle\/Oauth2Bundle\/Oauth2Bundle.html"," < Bundle",
                [        ]]        ]]        ]]        ]]        ]

