var tree = [["PantaRei",,"",
                [["Bundle",,"",
                [["OAuth2Bundle","PantaRei\/Bundle\/OAuth2Bundle.html","",
                [["Controller","PantaRei\/Bundle\/OAuth2Bundle\/Controller.html","",
                [["AuthorizeController","PantaRei\/Bundle\/OAuth2Bundle\/Controller\/AuthorizeController.html"," < Controller",
                [        ]],["ResourceController","PantaRei\/Bundle\/OAuth2Bundle\/Controller\/ResourceController.html"," < Controller",
                [        ]],["TokenController","PantaRei\/Bundle\/OAuth2Bundle\/Controller\/TokenController.html"," < Controller",
                [        ]]        ]],["DependencyInjection","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection.html","",
                [["Security",,"",
                [["Factory","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory.html","",
                [["ResourceFactory","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/ResourceFactory.html","",
                [        ]],["TokenFactory","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/TokenFactory.html","",
                [        ]]        ]]        ]],["Configuration","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection\/Configuration.html","",
                [        ]],["OAuth2Extension","PantaRei\/Bundle\/OAuth2Bundle\/DependencyInjection\/OAuth2Extension.html"," < Extension",
                [        ]]        ]],["Entity","PantaRei\/Bundle\/OAuth2Bundle\/Entity.html","",
                [["AccessToken","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/AccessToken.html","",
                [        ]],["AccessTokenManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/AccessTokenManager.html"," < EntityRepository",
                [        ]],["Authorize","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/Authorize.html","",
                [        ]],["AuthorizeManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/AuthorizeManager.html"," < EntityRepository",
                [        ]],["Client","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/Client.html","",
                [        ]],["ClientManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/ClientManager.html"," < EntityRepository",
                [        ]],["Code","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/Code.html","",
                [        ]],["CodeManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/CodeManager.html"," < EntityRepository",
                [        ]],["ModelManagerFactory","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/ModelManagerFactory.html","",
                [        ]],["RefreshToken","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/RefreshToken.html","",
                [        ]],["RefreshTokenManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/RefreshTokenManager.html"," < EntityRepository",
                [        ]],["Scope","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/Scope.html","",
                [        ]],["ScopeManager","PantaRei\/Bundle\/OAuth2Bundle\/Entity\/ScopeManager.html"," < EntityRepository",
                [        ]]        ]],["OAuth2Bundle","PantaRei\/Bundle\/OAuth2Bundle\/OAuth2Bundle.html"," < Bundle",
                [        ]]        ]]        ]]        ]]        ]

