var tree = [["Pantarei",,"",
                [["Bundle",,"",
                [["Oauth2Bundle","Pantarei\/Bundle\/Oauth2Bundle.html","",
                [["Controller","Pantarei\/Bundle\/Oauth2Bundle\/Controller.html","",
                [["AuthorizeController","Pantarei\/Bundle\/Oauth2Bundle\/Controller\/AuthorizeController.html"," < Controller",
                [        ]],["TokenController","Pantarei\/Bundle\/Oauth2Bundle\/Controller\/TokenController.html"," < Controller",
                [        ]]        ]],["DependencyInjection","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection.html","",
                [["Security",,"",
                [["Factory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory.html","",
                [["ResourceFactory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory\/ResourceFactory.html","",
                [        ]],["TokenFactory","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Security\/Factory\/TokenFactory.html","",
                [        ]]        ]]        ]],["Configuration","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Configuration.html","",
                [        ]],["Oauth2Extension","Pantarei\/Bundle\/Oauth2Bundle\/DependencyInjection\/Oauth2Extension.html"," < Extension",
                [        ]]        ]],["Model","Pantarei\/Bundle\/Oauth2Bundle\/Model.html","",
                [["AbstractAccessToken","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractAccessToken.html","",
                [        ]],["AbstractAuthorize","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractAuthorize.html","",
                [        ]],["AbstractClient","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractClient.html","",
                [        ]],["AbstractCode","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractCode.html","",
                [        ]],["AbstractRefreshToken","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractRefreshToken.html","",
                [        ]],["AbstractScope","Pantarei\/Bundle\/Oauth2Bundle\/Model\/AbstractScope.html","",
                [        ]],["ModelManagerFactory","Pantarei\/Bundle\/Oauth2Bundle\/Model\/ModelManagerFactory.html","",
                [        ]]        ]],["Oauth2Bundle","Pantarei\/Bundle\/Oauth2Bundle\/Oauth2Bundle.html"," < Bundle",
                [        ]]        ]]        ]]        ]]        ]

