var tree = [["AuthBucket",,"",
                [["Bundle",,"",
                [["OAuth2Bundle","AuthBucket\/Bundle\/OAuth2Bundle.html","",
                [["Controller","AuthBucket\/Bundle\/OAuth2Bundle\/Controller.html","",
                [["AuthorizeController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/AuthorizeController.html"," < Controller",
                [        ]],["DebugController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/DebugController.html"," < Controller",
                [        ]],["TokenController","AuthBucket\/Bundle\/OAuth2Bundle\/Controller\/TokenController.html"," < Controller",
                [        ]]        ]],["DependencyInjection","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection.html","",
                [["Security",,"",
                [["Factory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory.html","",
                [["ResourceFactory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/ResourceFactory.html","",
                [        ]],["TokenFactory","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Security\/Factory\/TokenFactory.html","",
                [        ]]        ]]        ]],["AuthBucketOAuth2Extension","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/AuthBucketOAuth2Extension.html"," < Extension",
                [        ]],["Configuration","AuthBucket\/Bundle\/OAuth2Bundle\/DependencyInjection\/Configuration.html","",
                [        ]]        ]],["Entity","AuthBucket\/Bundle\/OAuth2Bundle\/Entity.html","",
                [["AccessToken","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AccessToken.html","",
                [        ]],["AccessTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AccessTokenRepository.html"," < EntityRepository",
                [        ]],["Authorize","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Authorize.html","",
                [        ]],["AuthorizeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/AuthorizeRepository.html"," < EntityRepository",
                [        ]],["Client","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Client.html","",
                [        ]],["ClientRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ClientRepository.html"," < EntityRepository",
                [        ]],["Code","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Code.html","",
                [        ]],["CodeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/CodeRepository.html"," < EntityRepository",
                [        ]],["ModelManagerFactory","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ModelManagerFactory.html","",
                [        ]],["RefreshToken","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/RefreshToken.html","",
                [        ]],["RefreshTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/RefreshTokenRepository.html"," < EntityRepository",
                [        ]],["Scope","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/Scope.html","",
                [        ]],["ScopeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Entity\/ScopeRepository.html"," < EntityRepository",
                [        ]]        ]],["Tests","AuthBucket\/Bundle\/OAuth2Bundle\/Tests.html","",
                [["Controller","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Controller.html","",
                [["AuthorizateControllerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Controller\/AuthorizateControllerTest.html"," < WebTestCase",
                [        ]],["DebugControllerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Controller\/DebugControllerTest.html"," < WebTestCase",
                [        ]],["TokenControllerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Controller\/TokenControllerTest.html"," < WebTestCase",
                [        ]]        ]],["Exception","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception.html","",
                [["AccessDeniedExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/AccessDeniedExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidClientExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/InvalidClientExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidGrantExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/InvalidGrantExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidRequestExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/InvalidRequestExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["InvalidScopeExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/InvalidScopeExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["ServerErrorExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/ServerErrorExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["TemporarilyUnavailableExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/TemporarilyUnavailableExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnauthorizedClientExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/UnauthorizedClientExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnsupportedGrantTypeExceptionTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/UnsupportedGrantTypeExceptionTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["UnsupportedResponseTypeTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/Exception\/UnsupportedResponseTypeTest.html"," < PHPUnit_Framework_TestCase",
                [        ]]        ]],["GrantType","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType.html","",
                [["AuthorizationCodeGrantTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/AuthorizationCodeGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["BarGrantTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/BarGrantTypeHandler.html","",
                [        ]],["ClientCredentialsGrantTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/ClientCredentialsGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooGrantTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/FooGrantTypeHandler.html","",
                [        ]],["GrantTypeHandlerFactoryTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/GrantTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["PasswordGrantTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/PasswordGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]],["RefreshTokenGrantTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/GrantType\/RefreshTokenGrantTypeHandlerTest.html"," < WebTestCase",
                [        ]]        ]],["ResponseType","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType.html","",
                [["BarResponseTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType\/BarResponseTypeHandler.html","",
                [        ]],["CodeResponseTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType\/CodeResponseTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooResponseTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType\/FooResponseTypeHandler.html","",
                [        ]],["ResponseTypeHandlerFactoryTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType\/ResponseTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["TokenResponseTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/ResponseType\/TokenResponseTypeHandlerTest.html"," < WebTestCase",
                [        ]]        ]],["TestBundle","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle.html","",
                [["Controller","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Controller.html","",
                [["SecurityController","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Controller\/SecurityController.html"," < Controller",
                [        ]]        ]],["DataFixtures",,"",
                [["ORM","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM.html","",
                [["AccessTokenFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/AccessTokenFixture.html","",
                [        ]],["AuthorizeFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/AuthorizeFixture.html","",
                [        ]],["ClientFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/ClientFixture.html","",
                [        ]],["CodeFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/CodeFixture.html","",
                [        ]],["RefreshTokenFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/RefreshTokenFixture.html","",
                [        ]],["ScopeFixture","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/DataFixtures\/ORM\/ScopeFixture.html","",
                [        ]]        ]]        ]],["Entity","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity.html","",
                [["AccessToken","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/AccessToken.html"," < AccessToken",
                [        ]],["AccessTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/AccessTokenRepository.html"," < AccessTokenRepository",
                [        ]],["Authorize","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/Authorize.html"," < Authorize",
                [        ]],["AuthorizeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/AuthorizeRepository.html"," < AuthorizeRepository",
                [        ]],["Client","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/Client.html"," < Client",
                [        ]],["ClientRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/ClientRepository.html"," < ClientRepository",
                [        ]],["Code","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/Code.html"," < Code",
                [        ]],["CodeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/CodeRepository.html"," < CodeRepository",
                [        ]],["RefreshToken","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/RefreshToken.html"," < RefreshToken",
                [        ]],["RefreshTokenRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/RefreshTokenRepository.html"," < RefreshTokenRepository",
                [        ]],["Scope","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/Scope.html"," < Scope",
                [        ]],["ScopeRepository","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/Entity\/ScopeRepository.html"," < ScopeRepository",
                [        ]]        ]],["TestBundle","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TestBundle\/TestBundle.html"," < Bundle",
                [        ]]        ]],["TokenType","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType.html","",
                [["BarModelManagerFactory","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/BarModelManagerFactory.html","",
                [        ]],["BarTokenTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/BarTokenTypeHandler.html","",
                [        ]],["BearerTokenTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/BearerTokenTypeHandlerTest.html"," < WebTestCase",
                [        ]],["FooModelManagerFactory","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/FooModelManagerFactory.html","",
                [        ]],["FooTokenTypeHandler","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/FooTokenTypeHandler.html","",
                [        ]],["MacTokenTypeHandlerTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/MacTokenTypeHandlerTest.html"," < WebTestCase",
                [        ]],["TokenTypeHandlerFactoryTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/TokenType\/TokenTypeHandlerFactoryTest.html"," < PHPUnit_Framework_TestCase",
                [        ]]        ]],["AutoloadTest","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/AutoloadTest.html"," < PHPUnit_Framework_TestCase",
                [        ]],["OAuth2Test","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/OAuth2Test.html"," < WebTestCase",
                [        ]],["WebTestCase","AuthBucket\/Bundle\/OAuth2Bundle\/Tests\/WebTestCase.html"," < KernelTestCase",
                [        ]]        ]],["AuthBucketOAuth2Bundle","AuthBucket\/Bundle\/OAuth2Bundle\/AuthBucketOAuth2Bundle.html"," < Bundle",
                [        ]]        ]]        ]]        ]]        ]

